# Generated by Django 2.0.3 on 2018-03-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
