# Generated by Django 2.0.3 on 2018-03-23 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='owner',
        ),
    ]
