# Generated by Django 2.0.3 on 2018-04-01 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_weddinginvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_inviting', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_invite', to='groups.Group')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_invited', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='weddinginvite',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='weddinginvite',
            name='group',
        ),
        migrations.RemoveField(
            model_name='weddinginvite',
            name='to_user',
        ),
        migrations.DeleteModel(
            name='WeddingInvite',
        ),
    ]
