# Generated by Django 2.0.3 on 2018-04-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_auto_20180401_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about_me',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='status',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
