# Generated by Django 2.0.3 on 2018-04-04 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_auto_20180404_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='role',
            new_name='user_role',
        ),
    ]
